export const ADD_THREAD = 'ADD_THREAD';

export const AUTH_USER = 'AUTH_USER';
export const REGISTER_USER = 'REGISTER_USER';
export const SET_USER_AUTH = 'SET_USER_AUTH';
export const USER_LOGOUT = 'USER_LOGOUT';
export const USER_LOGOUT_STATE_UPDATE = 'USER_LOGOUT_STATE_UPDATE';
export const AUTH_IN_PROCESS = 'AUTH_IN_PROCESS';

export const POST_IN_PROCESS = 'POST_IN_PROCESS';
export const POST_STATUS = 'POST_STATUS';
export const SET_POST = 'SET_POST';

export const ADD_ACTIVITY = 'ADD_ACTIVITY';
export const LOAD_ACTIVITIES = 'LOAD_ACTIVITIES';
export const LOAD_ACTIVITIES_DATA = 'LOAD_ACTIVITIES_DATA';
