export const ADD_ANNOTATION = 'ADD_ANNOTATION';
export const DELETE_ANNOTATION = 'DELETE_ANNOTATION';
export const UPDATED_ANNOTATION = 'UPDATED_ANNOTATION';

export const SET_USER_AFTER_LOGIN = 'SET_USER_AFTER_LOGIN';